# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ASGuy
tagline:          'AverageSecurityGuy'
url:              https://averagesecurityguy.github.io
baseurl:          /

author:
  name:           'Stephen Haywood'
  url:            https://twitter.com/averagesecguy

paginate:         5
